language: python
python:
  - "2.7"
  
install:
  - pip install codeclimate-test-reporter
  - pip install coveralls
  
after_success:
  - coveralls
  - codeclimate-test-reporter
  
script:
  coverage run --source=testtoolkit setup.py test